from ccminer import *
from claymore import *
from ethminer import *
from ewbf import *
from miner import *
from sgminer import *
from amdxmrig import *
from nvidiaxmrig import *
from castxmr import *
from cryptodredge import *
from phoenixminer import *
from trex import *
from avermore import *